DROP DATABASE IF EXISTS User
CREATE DATABASE User;

DROP DATABASE IF EXISTS Shoe
CREATE DATABASE Shoe;

DROP DATABASE IF EXISTS Trade
CREATE DATABASE Trade;

DROP DATABASE IF EXISTS shoe_trade
CREATE DATABASE shoe_trade;